services:
  coli-rich-dev:
    image: ghcr.io/gbv/coli-rich-web:dev
    volumes:
      - $DATA/coli-rich-dev/enrichments:/enrichments
    env_file:
      - $CONFIGS/coli-rich-dev.env
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx
