services:
  coli-rich-dev:
    image: ghcr.io/gbv/coli-rich-web
    volumes:
      - $CONFIGS/coli-rich-dev.json:/config/config.json
    environment:
      - VIRTUAL_HOST=coli-conc.gbv.de
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/coli-rich/dev/
      - VIRTUAL_DEST=/
      - BASE=/coli-rich/dev/
      - LOGIN=https://coli-conc.gbv.de/login
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx
