services:
  subjects-api:
    image: ghcr.io/gbv/subjects-api:main
    volumes:
      - $DATA/subjects-api:/data
    environment:
      - VIRTUAL_HOST=coli-conc.gbv.de
      - VIRTUAL_PORT=3141
      - VIRTUAL_PATH=/subjects/
      - VIRTUAL_DEST=/
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx
