services:
  mongo-dev:
    image: mongo:7
    container_name: mongo-dev
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - $DATA/mongo-dev:/data/db
      - $HOME/backup:/backup
    restart: unless-stopped
  
  mongo-setup-replica-set:
    image: mongo:7
    depends_on:
      - mongo-dev
    volumes: 
      - $CONFIGS/mongo-initdb.d:/docker-entrypoint-initdb.d
    restart: "no"

networks:
  default:
    external: true
    name: mongo-dev
