version: "3"

services:
  mongo:
    image: mongo:7
    volumes:
      - $DATA/mongo:/data/db
      - $HOME/backup:/backup
    restart: unless-stopped

networks:
  default:
    external: true
    name: mongo
