services:
  mongo:
    image: mongo:7
    volumes:
      - $DATA/mongo:/data/db
      - $HOME/backup:/backup
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped

networks:
  default:
    external: true
    name: mongo
