services:

  nginx-dev:
    image: nginxproxy/nginx-proxy
    container_name: nginx-dev
    volumes:
      - /run/user/$UID/docker.sock:/tmp/docker.sock:ro
      - $CONFIGS/nginx.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
      - $CONFIGS/nginx-dev/vhost.d:/etc/nginx/vhost.d:ro
    environment:
     - TRUST_DOWNSTREAM_PROXY=true
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx-dev
