services:
  jskos-server-ui-dev:
    image: ghcr.io/gbv/jskos-server-ui:dev
    networks:
      - nginx
    volumes:
      - $CONFIGS/jskos-server-ui-dev.json:/usr/share/nginx/html/config.json:ro
    environment:
      - |
        VIRTUAL_HOST_MULTIPORTS=
          coli-conc.gbv.de:
            "/jskos-server-ui-dev/":
              port: 80
              dest: "/"
            "/assets/":
              port: 80
            "/favicon.svg":
              port: 80
    restart: unless-stopped

networks:
  nginx:
    external: true
    name: nginx
