services:
  coli-rich:
    image: ghcr.io/gbv/coli-rich-web:main
    volumes:
      - $DATA/coli-rich/enrichments:/enrichments
    env_file:
      - $CONFIGS/coli-rich.env
    restart: unless-stopped
    labels:
      description: "Catalog enrichment via concordances"
      type: application

networks:
  default:
    external: true
    name: nginx
