version: "3"

services:
  coli-rich:
    image: ghcr.io/gbv/coli-rich:main
    # volumes:
    #   - $CONFIGS/coli-rich.json:/config/config.json
    environment:
      - VIRTUAL_HOST=coli-conc.gbv.de
      - VIRTUAL_PORT=3077
      - VIRTUAL_PATH=/coli-rich/app/
      - VIRTUAL_DEST=/
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx
