version: "3"

services:

  nginx:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /run/user/$UID/docker.sock:/tmp/docker.sock:ro
      - $CONFIGS/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx
