services:
  subjects-api-dev:
    image: ghcr.io/gbv/subjects-api:dev
    env_file:
      - $CONFIGS/subjects-api-dev.env
    volumes:
      - $DATA/subjects-api-dev:/data
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx
