services:
  cocoda:
    image: ghcr.io/gbv/cocoda-versions
    volumes:
      - $DATA/cocoda:/www/cocoda
      - $CONFIGS/cocoda:/configs
      - $DATA/cocoda.git:/root/cocoda
      # nfdi4objects logo
      - $CONFIGS/cocoda/nfdi4objects-logo.png:/www/cocoda/nfdi4objects/nfdi4objects-logo.png
    restart: unless-stopped
    environment:
      - TAGS=all
      - USE_SUBPATH=true
      - VIRTUAL_HOST=coli-conc.gbv.de
      - VIRTUAL_PATH=~^/cocoda/.+

networks:
  default:
    external: true
    name: nginx
