services:
  cocoda:
    image: ghcr.io/gbv/cocoda-versions
    volumes:
      - $DATA/cocoda:/www/cocoda
      - $CONFIGS/cocoda:/configs
      - $DATA/cocoda.git:/root/cocoda
    restart: unless-stopped
    environment:
      - TAGS=all
      - USE_SUBPATH=true
      - VIRTUAL_HOST=coli-conc.gbv.de
      - VIRTUAL_PATH=~^/cocoda/.+
    labels:
      description: "The Mapping Tool is the main application of the infrastructure we provide"
      type: application

networks:
  default:
    external: true
    name: nginx
