services:
  jskos-server-dev:
    image: ghcr.io/gbv/jskos-server:dev
    networks:
      - nginx
      - mongo
    volumes:
      - $CONFIGS/jskos-server-dev.json:/config/config.json
    environment:
      - VIRTUAL_HOST=coli-conc.gbv.de
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/dev-api/
      - VIRTUAL_DEST=/
    restart: unless-stopped

networks:
  nginx:
    external: true
    name: nginx
  mongo:
    external: true
    name: mongo
