services:
  jskos-proxy-dev:
    image: ghcr.io/gbv/jskos-proxy:dev
    environment:
      - CONFIG=uri.gbv.de+coli-conc
      - BASE=/terminology/
      - VIRTUAL_HOST=coli-conc.gbv.de
      - VIRTUAL_PORT=3555
      - VIRTUAL_PATH=/terminology/
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx
