services:
  login-server:
    image: ghcr.io/gbv/login-server:0.7
    networks:
      - default
      - nginx
      - mongo
    volumes:
      - $SECRETS/login-server:/config
      - $DATA/login-server/static:/usr/src/app/static
    env_file:
      - $CONFIGS/login-server.env
      - $SECRETS/login-server.env
    restart: unless-stopped

networks:
  default:
  nginx:
    external: true
    name: nginx
  mongo:
    external: true
    name: mongo
