services:
  wikidata-jskos:
    image: ghcr.io/gbv/wikidata-jskos
    env_file:
      - $CONFIGS/wikidata-jskos.env
      - $SECRETS/wikidata-jskos.env
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx
